services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=custom_network"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "3003:3003"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik-config.yml:/etc/traefik/traefik.yml:ro
      - ./data/certs/:/var/traefik/certs/:rw
    networks:
      - custom_network

networks:
  custom_network:
    external: true
