apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
        - name: video-streaming
          image: tushar2005/video_streaming:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8100
          volumeMounts:
            - name: video-storage
              mountPath: /app/myapp/static/
            - name: tls-certs-volume
              mountPath: /app/tls
              readOnly: true
          envFrom:
            - secretRef:
                name: video-stream-secret
          command: ["/entrypoint.sh"]
      volumes:
        - name: video-storage
          persistentVolumeClaim:
            claimName: video-stream-pvc
        - name: tls-certs-volume
          secret:
            secretName: tls-secret
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-stream-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming-service
spec:
  selector:
    app: video-streaming
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: LoadBalancer
