services:
  app:
    image: tushar2005/video_streaming:latest
    deploy:
      replicas: 5
    ports:
      - "8100:8100"
    volumes:
      - video_stream_volume:/app/myapp/static/
      - /var/my_cert/cert.pem:/app/cert.pem
      - /var/my_cert/key.pem:/app/key.pem
    secrets:
      - SECRET
      - PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_HOSTNAME
      - DB_NAME
      - DB_PORT
    entrypoint: ["/entrypoint.sh"]

volumes:
  video_stream_volume:
    driver: local

secrets:
  SECRET:
    external: true
  PORT:
    external: true
  DB_USERNAME:
    external: true
  DB_PASSWORD:
    external: true
  DB_HOSTNAME:
    external: true
  DB_NAME:
    external: true
  DB_PORT:
    external: true
