services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uploadPipeline
    restart: always
    ports:
      - "3002:3002"
    working_dir: /app
    volumes:
      - .:/app
      - /var/my_app/cert.pem:/app/.certs/cert.pem
      - /var/my_app/key.pem:/app/.certs/key.pem
    env_file:
        - .env
